# 科目表示用定数
CATEGORY1 = "Reading"
CATEGORY1_AR = "القراءة"
CATEGORY2 = "Writing"
CATEGORY2_AR = "الكتابة"
CATEGORY3 = "Conversation"
CATEGORY3_AR = "المحادثة والاستماع"
CATEGORY4 = "Grammer"
CATEGORY4_AR = "قواعد اللغة"
CATEGORY5 = "Supplement"
CATEGORY5_AR = "قصة هوندا"
