default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch("DB_MILAAHA_HOST") %>
  username: <%= ENV.fetch("DB_MILAAHA_USERNAME") %>
  password: <%= ENV.fetch("DB_MILAAHA_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_MILAAHA_DATABASE") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_MILAAHA_DATABASE") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_MILAAHA_DATABASE") %>
